"""replace thumbnail with thumbnail_index

Revision ID: 93af5e08b318
Revises: 9e2ee3c33772
Create Date: 2026-02-21 16:49:20.309909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93af5e08b318'
down_revision: Union[str, Sequence[str], None] = '9e2ee3c33772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    if conn.dialect.name == 'sqlite':
        cursor = conn.execute(sa.text("PRAGMA table_info(projects)"))
        columns = [row[1] for row in cursor.fetchall()]
    else:
        # PostgreSQL etc.: inspect would be needed
        from sqlalchemy import inspect
        columns = [c["name"] for c in inspect(conn).get_columns("projects")]

    if "thumbnail_index" not in columns:
        op.add_column('projects', sa.Column('thumbnail_index', sa.Integer(), nullable=False, server_default='0'))
    if "thumbnail" in columns:
        op.drop_column('projects', 'thumbnail')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('thumbnail', sa.TEXT(), nullable=True))
    op.drop_column('projects', 'thumbnail_index')
    # ### end Alembic commands ###
