"""replace thumbnail with thumbnail_index

Revision ID: 93af5e08b318
Revises: 9e2ee3c33772
Create Date: 2026-02-21 16:49:20.309909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93af5e08b318'
down_revision: Union[str, Sequence[str], None] = '9e2ee3c33772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('thumbnail_index', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('projects', 'thumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('thumbnail', sa.TEXT(), nullable=True))
    op.drop_column('projects', 'thumbnail_index')
    # ### end Alembic commands ###
